# Generated by Django 4.0.3 on 2022-04-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taansen', '0002_song_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_link',
        ),
    ]
