# Generated by Django 4.0.3 on 2022-04-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taansen', '0004_userinfo_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='authuser',
        ),
    ]
