# Generated by Django 4.0.3 on 2022-04-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taansen', '0006_profile_delete_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='song_history',
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_songs',
            field=models.ManyToManyField(to='taansen.song'),
        ),
    ]
