# Generated by Django 4.0.3 on 2022-04-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taansen', '0008_alter_profile_liked_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='song_history',
            field=models.ManyToManyField(related_name='song_history', to='taansen.song'),
        ),
    ]
