# Generated by Django 4.0.3 on 2022-04-17 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taansen', '0009_profile_song_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='song_history',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('song_history', models.ManyToManyField(to='taansen.song')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='taansen.history'),
        ),
    ]
