# Generated by Django 4.0.3 on 2022-04-17 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taansen', '0010_remove_profile_song_history_history_profile_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taansen.song')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='history',
        ),
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.ManyToManyField(related_name='history', through='taansen.Time', to='taansen.song'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.AddField(
            model_name='time',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taansen.profile'),
        ),
    ]
